services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: "npm run dev"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}